title : Chue10
timezone: America/Chicago
tagline: Chue10 Github page
author :
 name : Christopher Huerta
 email : chuer10@wgu.edu
 github : chue10
production_url : https://chue10.github.io/
BASE_PATH : https://chue10.github.io/	
