title : Chue10
tagline: Site Tagline
author :
 name : Christopher Huerta
 email : chuer10@wgu.edu
 github : chue10
permalink: https://chue10.github.io/
production_url : https://chue10.github.io/
BASE_PATH : https://chue10.github.io/	
