title : Chue10
tagline: Site Tagline
author :
 name : Christopher Huerta
 email : chuer10@wgu.edu
 github : chue10
production_url : https://chue10.github.io/myrepo
BASE_PATH : https://chue10.github.io/myrepo	
